Attributes: enums with additional metadata
ynput/ayon-backend pull request #314
Opened 2024-08-06 09:41 UTC by martastain

Adds `icon` and `color` to AttributeEnumItem model.

2024-09-18 07:28 UTC, martastain commented
@Innders Are we adding that priority built-in attribute?

2024-09-25 09:37 UTC, Innders requested changes

2024-09-25 09:37 UTC, Innders commented on setup/attributes.py
> +            {"value": "high", "label": "High", "color": "#ff0000"},
```suggestion
            {"value": "low", "label": "Low", "color": "#9FA7B1", "icon": "keyboard_arrow_down"},
            {"value": "normal", "label": "Normal", "color": "#9AC0E7", "icon": "check_indeterminate_small"},
            {"value": "high", "label": "High", "color": "#FFAD66", "icon": "keyboard_arrow_up"},
            {"value": "urgent", "label": "Urgent", "color": "#FF8585", "icon": "keyboard_double_arrow_up"},
```

2024-09-26 12:14 UTC, martastain commented
@Innders i've handled the way defaults propagate to the children entities, so it should now display correctly the default priority set in anatomy or set as default on the attribute. In order to rebuild the hierarchy on the project created before this attribute was introduced, it is necessary to run the setup process (make setup). that will be triggered during server update, so it shouldn't cause issues.

2024-09-30 07:29 UTC, merged